### ISSUE TITLE
Analise do HTML feito em sala de aula.

### ISSUE THREAD

**Issue by MOVelasco** [MatheusNfs/EstudoSaladeAula#1]
Olá Matheus.
Estou olhando primeiro arquivo que fizemos na nossa primeira aula de HTML, e o seu documento html, esta muito bem formatado e endentado, já que fizemos ele em Notepad++.
Algumas **observações:** você fez uso de TAGs (``<font> e <b>``) do HTML versão: 4.1 e nós em sala de aula só usamos da versão: 5. 
Ao invés de usar ``<b>`` use ``<strong>``, e não utilize a ``<font>``. Ok?

**Comment by MatheusNfs** [comment]
Blz
